import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import { env } from './configs/env.js';
import requestId from './middlewares/requestId.middleware.js';
import errorHandler from './middlewares/error.middleware.js';
import { rateLimit } from './middlewares/rateLimit.middleware.js';
import limits from './configs/rateLimit.js';
import { rejectUnsafeKeys } from './utils/sanitize.js';
import ApiError from './utils/ApiError.js';
import auth from './routes/auth.routes.js';
import users from './routes/user.routes.js';
import textbooks from './routes/textbook.routes.js';
import chapters from './routes/chapter.routes.js';
import patterns from './routes/pattern.routes.js';
import samples from './routes/samplePaper.routes.js';
import papers from './routes/questionPaper.routes.js';
import health from './routes/health.routes.js';
import admin from './routes/admin.routes.js';
import { requireAuth, requireRole } from './middlewares/auth.middleware.js';
import { resourceId } from './routes/shared.js';
import { job } from './controllers/questionPaper.controller.js';
import a from './utils/asyncHandler.js';
import { registry, allMetrics } from './services/operations/metrics.service.js';
export function createApp() {
  const app = express(); app.disable('x-powered-by');
  if (env.TRUST_PROXY) app.set('trust proxy', env.TRUST_PROXY.split(',').map(s => s.trim()));
  app.use(requestId, helmet());
  const origins = new Set(env.CORS_ORIGIN.split(',').map(s => s.trim()));
  app.use(cors({ origin: (origin, cb) => cb(origin && !origins.has(origin) ? new ApiError(403, 'Origin is not allowed', 'FORBIDDEN') : null, !origin || origins.has(origin)), credentials: false, allowedHeaders: ['Content-Type', 'Authorization', 'Idempotency-Key'], exposedHeaders: ['X-Request-Id', 'Retry-After', 'RateLimit-Limit', 'RateLimit-Remaining'] }));
  app.use('/api/v1/health', health);
  app.use(rateLimit('api-ip', req => req.ip, limits.global));
  app.use(express.json({ limit: '64kb' }));
  app.use((req, res, next) => { res.setHeader('Cache-Control', 'no-store'); try { rejectUnsafeKeys(req.body); rejectUnsafeKeys(req.query); next(); } catch (e) { next(e); } });
  for (const [path, router] of [['auth', auth], ['users', users], ['textbooks', textbooks], ['chapters', chapters], ['patterns', patterns], ['sample-papers', samples], ['question-papers', papers], ['admin', admin]]) app.use(`/api/v1/${path}`, router);
  app.get('/api/v1/generation-jobs/:id', requireAuth(), resourceId, a(job));
  app.get('/api/v1/metrics', requireAuth(), requireRole('admin'), a(async (_req, res) => res.type(registry.contentType).send(await allMetrics())));
  app.use((_req, _res, next) => next(new ApiError(404, 'Resource not found', 'RESOURCE_NOT_FOUND'))); app.use(errorHandler);
  return app;
}
