import { Router } from 'express';
import { z } from 'zod';
import * as admin from '../controllers/admin.controller.js';
import { upload } from '../middlewares/upload.middleware.js';
import { rateLimit } from '../middlewares/rateLimit.middleware.js';
import limits from '../configs/rateLimit.js';
import { requireAuth, requireRole } from '../middlewares/auth.middleware.js';
import { validate } from '../middlewares/validate.middleware.js';
import { catalogBody, chapterBody } from '../utils/validators.js';
import { resourceId } from './shared.js';
import * as c from '../controllers/textbook.controller.js';
import a from '../utils/asyncHandler.js';
const r = Router(); r.use(requireAuth(), requireRole('admin'));
r.post('/textbooks', validate(catalogBody), a(c.create));
r.patch('/textbooks/:id', resourceId, validate(catalogBody.partial()), a(c.edit));
r.delete('/textbooks/:id', resourceId, a(c.remove));
r.post('/textbooks/:id/chapters', resourceId, validate(chapterBody), a(c.addChapter));
r.patch('/chapters/:id', resourceId, validate(chapterBody.partial()), a(c.editChapter));
r.post('/textbooks/:id/content', resourceId, rateLimit('upload', req => req.user.id, limits.upload), upload('book'), a(admin.uploadContent));
r.post('/sources/:source/sync', validate(z.object({ source: z.enum(['diksha', 'ncert']) }).strict(), 'params'), a(admin.sync));
export default r;
