import { Router } from 'express';
import { z } from 'zod';
import { requireAuth } from '../middlewares/auth.middleware.js';
import { validate } from '../middlewares/validate.middleware.js';
import { rateLimit } from '../middlewares/rateLimit.middleware.js';
import limits from '../configs/rateLimit.js';
import { listQuery, generationBody } from '../utils/validators.js';
import { resourceId } from './shared.js';
import * as c from '../controllers/questionPaper.controller.js';
import a from '../utils/asyncHandler.js';
const r = Router(); r.use(requireAuth());
const generationLimit = rateLimit('generation', req => req.user.id, limits.generation, 'GENERATION_LIMIT_REACHED');
r.post('/generate', validate(generationBody), generationLimit, a(c.generate));
r.get('/', validate(listQuery, 'query'), a(c.list));
r.get('/:id', resourceId, a(c.details)); r.delete('/:id', resourceId, a(c.remove));
r.post('/:id/regenerate', resourceId, validate(z.object({}).strict()), generationLimit, a(c.regenerate));
r.get('/:id/answer-key', resourceId, a(c.answerKey));
r.get('/:id/pdf', resourceId, validate(z.object({ kind: z.enum(['question-paper', 'answer-key']).default('question-paper') }).strict(), 'query'), a(c.pdf));
export default r;
