import { Router } from 'express';
import { z } from 'zod';
import * as c from '../controllers/textbook.controller.js';
import { requireAuth } from '../middlewares/auth.middleware.js';
import { validate } from '../middlewares/validate.middleware.js';
import { upload } from '../middlewares/upload.middleware.js';
import { rateLimit } from '../middlewares/rateLimit.middleware.js';
import limits from '../configs/rateLimit.js';
import { catalogQuery, listQuery, uploadBookBody } from '../utils/validators.js';
import { resourceId } from './shared.js';
import a from '../utils/asyncHandler.js';
const r = Router(); r.use(requireAuth());
r.get('/', validate(catalogQuery, 'query'), a(c.list));
r.get('/recommended', validate(catalogQuery, 'query'), a(c.recommended));
r.post('/resolve-qr', validate(z.object({ code: z.string().trim().min(1).max(500) }).strict()), a(c.resolve));
r.post('/upload', rateLimit('upload', req => req.user.id, limits.upload), upload('book'), validate(uploadBookBody), a(c.upload));
r.get('/:id', resourceId, a(c.details));
r.get('/:id/chapters', resourceId, validate(listQuery, 'query'), a(c.chapters));
export default r;
